import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Geist Variable", "system-ui", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        surface: {
          DEFAULT: "hsl(var(--surface) / <alpha-value>)",
          raised: "hsl(var(--surface-raised) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        destructive: "hsl(var(--destructive))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        favorite: "hsl(var(--favorite) / <alpha-value>)",
        rating: "hsl(var(--rating) / <alpha-value>)",
        teal: {
          50: "hsl(var(--teal-50) / <alpha-value>)",
          100: "hsl(var(--teal-100) / <alpha-value>)",
          200: "hsl(var(--teal-200) / <alpha-value>)",
          300: "hsl(var(--teal-300) / <alpha-value>)",
          400: "hsl(var(--teal-400) / <alpha-value>)",
          500: "hsl(var(--teal-500) / <alpha-value>)",
          600: "hsl(var(--teal-600) / <alpha-value>)",
          700: "hsl(var(--teal-700) / <alpha-value>)",
          800: "hsl(var(--teal-800) / <alpha-value>)",
          900: "hsl(var(--teal-900) / <alpha-value>)",
        },
        champagne: {
          50: "hsl(var(--champagne-50) / <alpha-value>)",
          100: "hsl(var(--champagne-100) / <alpha-value>)",
          200: "hsl(var(--champagne-200) / <alpha-value>)",
          300: "hsl(var(--champagne-300) / <alpha-value>)",
          400: "hsl(var(--champagne-400) / <alpha-value>)",
          500: "hsl(var(--champagne-500) / <alpha-value>)",
          600: "hsl(var(--champagne-600) / <alpha-value>)",
          700: "hsl(var(--champagne-700) / <alpha-value>)",
          800: "hsl(var(--champagne-800) / <alpha-value>)",
          900: "hsl(var(--champagne-900) / <alpha-value>)",
        },
        amber: {
          50: "hsl(var(--amber-50) / <alpha-value>)",
          100: "hsl(var(--amber-100) / <alpha-value>)",
          200: "hsl(var(--amber-200) / <alpha-value>)",
          300: "hsl(var(--amber-300) / <alpha-value>)",
          400: "hsl(var(--amber-400) / <alpha-value>)",
          500: "hsl(var(--amber-500) / <alpha-value>)",
          600: "hsl(var(--amber-600) / <alpha-value>)",
          700: "hsl(var(--amber-700) / <alpha-value>)",
          800: "hsl(var(--amber-800) / <alpha-value>)",
          900: "hsl(var(--amber-900) / <alpha-value>)",
        },
        ember: {
          50: "hsl(var(--ember-50) / <alpha-value>)",
          100: "hsl(var(--ember-100) / <alpha-value>)",
          200: "hsl(var(--ember-200) / <alpha-value>)",
          300: "hsl(var(--ember-300) / <alpha-value>)",
          400: "hsl(var(--ember-400) / <alpha-value>)",
          500: "hsl(var(--ember-500) / <alpha-value>)",
          600: "hsl(var(--ember-600) / <alpha-value>)",
          700: "hsl(var(--ember-700) / <alpha-value>)",
          800: "hsl(var(--ember-800) / <alpha-value>)",
          900: "hsl(var(--ember-900) / <alpha-value>)",
        },
        crimson: {
          50: "hsl(var(--crimson-50) / <alpha-value>)",
          100: "hsl(var(--crimson-100) / <alpha-value>)",
          200: "hsl(var(--crimson-200) / <alpha-value>)",
          300: "hsl(var(--crimson-300) / <alpha-value>)",
          400: "hsl(var(--crimson-400) / <alpha-value>)",
          500: "hsl(var(--crimson-500) / <alpha-value>)",
          600: "hsl(var(--crimson-600) / <alpha-value>)",
          700: "hsl(var(--crimson-700) / <alpha-value>)",
          800: "hsl(var(--crimson-800) / <alpha-value>)",
          900: "hsl(var(--crimson-900) / <alpha-value>)",
        },
        cinema: {
          50: "hsl(var(--cinema-50) / <alpha-value>)",
          100: "hsl(var(--cinema-100) / <alpha-value>)",
          200: "hsl(var(--cinema-200) / <alpha-value>)",
          300: "hsl(var(--cinema-300) / <alpha-value>)",
          400: "hsl(var(--cinema-400) / <alpha-value>)",
          500: "hsl(var(--cinema-500) / <alpha-value>)",
          600: "hsl(var(--cinema-600) / <alpha-value>)",
          700: "hsl(var(--cinema-700) / <alpha-value>)",
          800: "hsl(var(--cinema-800) / <alpha-value>)",
          900: "hsl(var(--cinema-900) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
